#! /bin/csh

#snuff GetCorSoundingsByFtp.py

GetCorSoundingsByFtp.py --debug --pastSecs=108000 \
    --ftpServer ftp.eol.ucar.edu \
    --ftpUser relampago18 \
    --ftpPasswd gr@N!20 \
    --sourceDir sounding/SMN/COR \
    --targetDir /home/storm/relops/soundings/SMN/COR \
    --tmpDir /home/storm/relops/soundings/SMN/tmp \
    |& LogFilter -d $ERRORS_LOG_DIR -p GetCorSoundingsByFtp >& /dev/null &

